# Generated by Django 5.0.4 on 2024-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10, verbose_name='Департамент')),
                ('sector', models.CharField(max_length=50, verbose_name='Полное наименование отдела/сектора')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('tab_number', models.CharField(max_length=7, verbose_name='Табельный номер')),
                ('mail', models.EmailField(max_length=30, verbose_name='Рабочая почта')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Рабочий телефон')),
                ('service', models.CharField(choices=[('Выберите услугу', 'Выберите услугу'), ('Интернет', 'Интернет'), ('Телефония', 'Телефония')], default='Выберите услугу', max_length=20, verbose_name='Услуга')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес установки оборудования')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата составления заявки')),
                ('komm', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
