# Generated by Django 5.0.4 on 2024-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.BooleanField(choices=[(0, 'Новая'), (1, 'Выполненная')], default=0, verbose_name='Статус заявки'),
        ),
    ]
